language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    chisel/target
    context-dependent-environments/target
    groundtest/target
    hardfloat/target
    junctions/target
    project/project/target
    project/target
    rocket/target
    target
    uncore/target
    zscale/target

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  matrix:
    - CONFIG=DefaultConfig
    - CONFIG=RoccExampleConfig
    - CONFIG=DmaControllerConfig
    - CONFIG=MemtestConfig
    - CONFIG=MemtestL2Config
    - CONFIG=BroadcastRegressionTestConfig
    - CONFIG=CacheRegressionTestConfig
    - CONFIG=UnitTestConfig
    - CONFIG=SplitL2MetadataTestConfig

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - hurricane

before_install:
  - rm riscv-tools/.travis.yml
  - export CXX=g++-4.8 CC=gcc-4.8

script:
  - make vsim-verilog -C regression CONFIG=$CONFIG TORTURE_CONFIG=default CHISEL_VERSION=3
  - make fsim-verilog -C regression CONFIG=$CONFIG TORTURE_CONFIG=default
  - make emulator-ndebug -C regression CONFIG=$CONFIG TORTURE_CONFIG=default
  - make emulator-asm-tests   -C regression CONFIG=$CONFIG TORTURE_CONFIG=default
  - make emulator-bmark-tests -C regression CONFIG=$CONFIG TORTURE_CONFIG=default -j1

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
